apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: bggappv1-deploy
  name: bggappv1-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bggappv1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bggappv1
    spec:
      containers:
      - image: stackupiss/bgg-backend:v1
        name: bgg-backend
        resources: {}
        args: ["--prefix", "/v1"]
        resources:
          requests:
            cpu: 100m
            memory: 16M
        ports:
        - containerPort: 3306
        envFrom:
        - configMapRef:
            name: bgg-cm
        - secretRef:
            name: bgg-secret
        livenessProbe:
              httpGet:
                 path: /v1/healthz
                 port: 3000
              failureThreshold: 3
              periodSeconds: 30
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: bggappv1-svc
  name: bggappv1-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: bggappv1
  type: ClusterIP

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: bggappv1-hpa
  labels:
    app: bggappv1-hpa
spec:
  minReplicas: 1
  maxReplicas: 4
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bggappv1-deploy
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 90
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: bggappv2-deploy
  name: bggappv2-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bggappv2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bggappv2
    spec:
      containers:
      - image: stackupiss/bgg-backend:v2
        name: bgg-backend
        resources: {}
        args: ["--prefix", "/v2"]
        ports:
        - containerPort: 3306
        envFrom:
        - configMapRef:
            name: bgg-cm
        - secretRef:
            name: bgg-secret
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: bggappv2-svc
  name: bggappv2-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: bggappv2
  type: ClusterIP