apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: bggapp-svc
  name: bggapp-svc
  namespace: bggns
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: bggapp
  type: LoadBalancer
status:
  loadBalancer: {}
