apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: bggapp-deploy
  name: bggapp-deploy
  namespace: bggns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bggapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bggapp
    spec:
      containers:
      - image: stackupiss/bgg-backend:v1
        name: bgg-backend
        resources: {}
        ports:
        - containerPort: 3306
        envFrom:
        - configMapRef:
            name: bgg-cm
        - secretRef:
            name: bgg-secret
status: {}


