apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: bggdb-svc
  name: bggdb-svc
  namespace: bggns
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: bggdb
  type: ClusterIP
status:
  loadBalancer: {}
