---
apiVersion: v1
kind: ConfigMap
metadata:
   name: wp-cm
   labels:
      name: wp-cm
data:
  WORDPRESS_DB_HOST: wordpress-mysql
---
apiVersion: v1
kind: Secret
metadata:
  name: wp-secret
  labels:
    name: wp-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: Y2hhbmdlaXQ=
  WORDPRESS_DB_PASSWORD: Y2hhbmdlaXQ=
---